# Hyprpaper config (DP-1 + left monitor)

preload = ~/Pictures/wallpapers/landscape1.jpg

# Set wallpaper per monitor
wallpaper = DP-1,~/Pictures/wallpapers/landscape1.jpg
wallpaper = HDMI-A-2,~/Pictures/wallpapers/landscape1.jpg

# Optional: keep hyprpaper alive
ipc = on

